export const en = {
  // Common & Navigation
  common: {
    appName: 'Ledger',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    or: 'OR',
    logout: 'Log Out',
    settings: 'Settings',
    searchPlaceholder: 'Search transactions, assets...',
    copied: 'Copied!',
    language: 'Language',
    english: 'English',
    indonesian: 'Bahasa Indonesia',
  },

  // Welcome Screen
  welcome: {
    headline: 'Your money,\nall in one place.',
    tagline: 'Manage Rupiah, USDT & USDC with ease.',
    getStarted: 'Get Started',
    getStartedSubtitle: 'Join thousands managing their wallet securely.',
    createAccount: 'Create Account',
    logIn: 'Log In',
    continueWithGoogle: 'Continue with Google',
    badgeTransfer: '💸  Instant Transfer',
    badgeSecurity: '🔒  2FA Protected',
    badgeSwap: '🔄  Crypto Swap',
    legalDisclaimer: 'By continuing, you agree to our Terms & Privacy Policy.',
  },

  // Auth (Login & Register)
  auth: {
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Access your secure financial dashboard',
    createAccountTitle: 'Create Account',
    registerSubtitle: 'Join Ledger to manage your assets securely',
    usernameLabel: 'USERNAME',
    usernamePlaceholder: 'E.g. johndoe',
    emailLabel: 'EMAIL ADDRESS',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'PASSWORD (MIN 6 CHARACTERS)',
    passwordPlaceholder: '••••••••',
    twoFactorVerification: '2FA Verification',
    twoFactorSubtitle: 'Enter the 6-digit code generated by your authenticator app',
    otpLabel: 'OTP CODE',
    verifyCode: 'Verify Code',
    backToLogin: 'Back to Log In',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    logIn: 'Log In',
    registerSuccess: 'Registration successful! Please log in with your new account.',
  },

  // Dashboard
  dashboard: {
    estimatedPortfolio: 'ESTIMATED PORTFOLIO VALUE',
    profitLoss: 'Profit/Loss',
    allTime: 'All time',
    filterAll: 'All',
    filterCrypto: 'Crypto',
    filterFiat: 'Fiat',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    yourAssets: 'Your Assets',
    quickTransfer: 'Transfer',
    quickTopUp: 'Top Up',
    quickSwap: 'Swap',
    quickWithdraw: 'Withdraw',
    transferDesc: 'Send funds instantly',
    topUpDesc: 'Add IDR via Midtrans',
    swapDesc: 'Instant rate exchange',
    withdrawDesc: 'Cash out to bank/wallet',
    noTransactions: 'No recent transactions yet.',
  },

  // Crypto Screen
  crypto: {
    cryptoTitle: 'Crypto Stablecoins',
    cryptoSubtitle: 'Deposit & Withdraw USDT/USDC on-chain',
    depositTab: 'Deposit',
    withdrawTab: 'Withdraw',
    selectAsset: 'Select Asset',
    networkNotice: 'POLYGON AMOY TESTNET',
    depositAddress: 'Your Deposit Address',
    copyAddress: 'Copy Wallet Address',
    noAddress: 'Deposit address not available',
    recipientAddress: 'RECIPIENT ADDRESS (EVM)',
    recipientPlaceholder: '0x...',
    withdrawAmount: 'WITHDRAW AMOUNT',
    minimumWithdraw: 'Minimum withdrawal: 1.0',
    availableBalance: 'Available',
    submitWithdrawal: 'Submit Crypto Withdrawal',
  },

  // Swap Screen
  swap: {
    swapTitle: 'Instant Swap',
    swapSubtitle: 'Exchange IDR, USDT, & USDC instantly at live rates',
    payFrom: 'PAY FROM',
    receiveTo: 'RECEIVE TO',
    balance: 'Balance',
    currentRate: 'Current Asset Pairing',
    swapFee: 'Swap Fee (0.5%)',
    performSwap: 'Perform Swap',
    insufficientBalance: 'Insufficient Balance',
  },

  // TopUp Screen
  topup: {
    topUpTitle: 'Top Up IDR',
    enterAmount: 'ENTER AMOUNT TO TOP UP',
    quickSelect: 'Quick Select Amount',
    notesLabel: 'NOTES (OPTIONAL)',
    notesPlaceholder: 'E.g. Monthly top up',
    continuePayment: 'Continue to Payment',
  },

  // History Screen
  history: {
    historyTitle: 'Transaction History',
    allTypes: 'All Types',
    transfers: 'Transfers',
    topUps: 'Top Ups',
    withdrawals: 'Withdrawals',
    swaps: 'Swaps',
  },

  // Settings Screen
  settings: {
    settingsTitle: 'Account Settings',
    profileSection: 'Profile Information',
    securitySection: 'Security & 2FA',
    preferencesSection: 'Preferences & Appearance',
    themeMode: 'Theme Mode',
    languagePreference: 'Language Preference',
    languageDesc: 'Choose your preferred display language',
    enable2FA: 'Enable 2FA Authentication',
    disable2FA: 'Disable 2FA Authentication',
    logoutBtn: 'Log Out of Ledger',
    appVersion: 'Ledger Hybrid Wallet v1.0.0',
  },
};

export type TranslationKeys = typeof en;
